### ISSUE TITLE
Error when posting

### ISSUE THREAD

**Issue by djselzlein** [kaburkett/LinkedIn-Advanced-Share#1]
I tried to post to LinkedIn using the available online version: http://datopstech.com/linkedin-share-tool/

When I submit there is a JavaScript error: Uncaught ReferenceError: title is not defined
Debugging your JavaScript I found the error and mocked a solution so I could post successfully.

If you would like so, I could help fixing this problem.

**Comment by kaburkett** [comment]
Thanks for caching this. Title no longer shows on the feed so I may have removed the attribute in the data I send. I will take a look!

Kyle

**Comment by djselzlein** [comment]
Thank you!

**Comment by kaburkett** [comment]
Thanks for reporting, pushed a working fix
